2023.05.10_Django/day4/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path("", views.index, name="list"),
    path('<int:id>/', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    path('create/form/', views.create_form, name="create_form"),
    path('create/form2/', views.create_form2, name="create_form2"),
]

2023.05.10_Django/day4/counter/urls.py
from django.urls import path
from django.http import HttpResponse
def cookie_counter(req):
    visits = int(req.COOKIES.get('visits', 0)) + 1
    res = HttpResponse(f"cookie: {visits}")
    res.set_cookie('visits', visits)
    return res

def session_counter(req):
    req.session['count'] = req.session.get('count', 0) + 1
    return HttpResponse(f"session: {req.session['count']}")
urlpatterns = [
    path('cookie/', cookie_counter),
    path('session/', session_counter),
]

2023.05.10_Django/day4/day4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse

def profile(req):
     return HttpResponse(f"{req.user.username}, {req.user.email}")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include('blog.urls')),
    path("counter/", include('counter.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', profile),
]

2023.05.10_Django/day4/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    published_at = models.DateField(null=True)
    def __str__(self):
        return self.title
    

# class Category(models.Model):
#     name = models.CharField(max_length=100)
#     def __str__(self):
#         return self.name
    

2023.05.10_Django/day4/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    publish_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return (self.publish_date < timezone.now() and
                self.publish_date >= timezone.now() - datetime.timedelta(days=1))
    def __str__(self):
        return self.question_text
        
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return f"{self.question} : {self.choice_text}"

2023.05.10_Django/day4/blog/forms.py
# blog/forms.py
from django import forms
from . import models

class PostForm(forms.Form):
    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea())
    published = forms.DateField()

class PostModelForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ('title', 'content', 'published_at')

2023.05.10_Django/day4/blog/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseNotFound, Http404
from . import models
from . import forms

# Create your views here.
def index(req):
    posts = models.Post.objects.all()
    return render(req, 'blog/index.html', {'post_list' : posts})

def detail(req, id):
    try:
        post = models.Post.objects.get(id=id)
    except Exception as e:
        return HttpResponseNotFound("그런 글은 없습니다.")
    return render(req, "blog/detail.html", {"post" : post})

def create(req):
    if req.method == 'POST':
        new_post = models.Post(
            title = req.POST.get('title'),
            content = req.POST.get('content')
        )
        new_post.save()
        return redirect(reverse('blog:list'))
    return render(req, 'blog/create.html')

def create_form(req):
    if req.method == 'POST':
        form = forms.PostForm(req.POST)
        if form.is_valid():
            new_post = models.Post(
                title = form.cleaned_data['title'],
                content = form.cleaned_data['content'],
                published_at = form.cleaned_data['published']
            )
            new_post.save()
            return redirect(reverse('blog:list'))
    else:
        form = forms.PostForm()

    return render(req, 'blog/create_form.html', {'form' : form})

def create_form2(req):
    if req.method == 'POST':
        form = forms.PostModelForm(req.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('blog:list'))
    else:
        form = forms.PostModelForm()

    return render(req, 'blog/create_form.html', {'form' : form})

2023.05.10_Django/day4/counter/views.py
from django.shortcuts import render

# Create your views here.

2023.05.10_Django/day4/polls/views.py
from django.shortcuts import render

# Create your views here.

2023.05.10_Django/day4/blog/templates/blog/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog - Post Create</title>
</head>
<body>
    <h1>Post Create</h1>
    <form method="post">
        {% csrf_token %}
        <div><input type="text" name="title" maxlength="100"></div>
        <div><textarea name="content" cols="40" rows="10"></textarea></div>
        <div><input type="submit" value="저장"></div>
    </form>
</body>
</html>
<a href='{% url 'blog:list' %}'>블로그 목록 보기</a>

2023.05.10_Django/day4/blog/templates/blog/create_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog - Post Create</title>
</head>
<body>
    <h1>Post Create</h1>
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <div><input type="submit" value="저장"></div>
    </form>
</body>
</html>
<a href='{% url 'blog:list' %}'>블로그 목록 보기</a>

2023.05.10_Django/day4/blog/templates/blog/detail.html
<h1>{{ post.title }}</h1>
<small>{{ post.published_at }}</small>
<hr>
<p>{{ post.content }}</p>
<hr>
<a href='{% url 'blog:list' %}'>블로그 목록 보기</a>

2023.05.10_Django/day4/blog/templates/blog/index.html
<h1><a href='{% url 'blog:list' %}'>블로그 목록 보기</a></h1>
<ul>
    {% for p in post_list %}
    <li>
        {% comment %} <a href="/blog/{{ p.id }}">{{ p.id }}. {{ p.title }}</a> {% endcomment %}
        <a href="{% url 'blog:detail' p.id %}">{{ p.id }}. {{ p.title }}</a>
    </li>
    {% endfor %}
</ul>
<hr>
{% comment %} <a href="/blog/create/">새글쓰기</a> {% endcomment %}
<a href="{% url 'blog:create' %}">새글쓰기1</a>
<a href="{% url 'blog:create_form' %}">새글쓰기2</a>
<a href="{% url 'blog:create_form2' %}">새글쓰기3</a>