2023.05.10_Django/day3/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),
]

2023.05.10_Django/day3/day3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include('blog.urls')),
]

2023.05.10_Django/day3/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    published_at = models.DateField(null=True)
    def __str__(self):
        return self.title
    

class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    

2023.05.10_Django/day3/school/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    year = models.IntegerField()
    def __str__(self):
        return f"{self.name}, {self.year}"

class Book(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    def __str__(self):
        return self.title

class Course(models.Model):
    title = models.CharField(max_length=100)
    students = models.ManyToManyField(Student)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    

2023.05.10_Django/day3/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest
from . import models

def post_list(req):
   posts = models.Post.objects.all()
   return render(req, 'index.html', { 'post_list': posts })

def post_detail(req, id):
    posts = models.Post.objects.all()
    post = models.Post.objects.get(id=id)
    return render(req, 'detail.html', {
        'post_list' : posts,
        'post' : post
    })
def post_detail(req: HttpRequest, id: int) -> HttpResponse:
   post = models.Post.objects.get(id=id)
   return render(req, 'detail.html', { 'post': post })

2023.05.10_Django/day3/blog/templates/detail.html
<!DOCTYPE html>
<html lang="kr">
<head>
   <meta charset="UTF-8">
   <title>Mysite | Blog</title>
   <h1><a href='/blog/'>Post List</a></h1>
</head>
<body>
   <h1>{{ post.title }}</h1>
   <div>{{ post.content }}</div>
</body>
</html>

2023.05.10_Django/day3/blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog - Post List</title>
</head>
<body>
    <h1>Post List</h1>
    <ul>
        {% for p in post_list %}
           <li><a href="{%url 'blog:post_detail' p.id %}">{{ p.id }}. {{ p.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>